**PyTorch Fundamentals**

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/fbourgey/fre-gy-7773-mlfe/blob/main/09_pytorch_fundamentals_solution.ipynb)


### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you are using. We will be using the PyTorch documentation a lot throughout the rest of this course. Here are some important sections of the PyTorch documentation to be familiar with:

  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).


### 2. Create a random tensor with shape `(7, 7)`.


In [16]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x.shape

torch.Size([7, 7])

In [17]:
type(x)

torch.Tensor

In [14]:
torch.__version__

'2.8.0'

In [18]:
torch.randn(7, 7)

tensor([[-0.0879,  0.9981, -0.0605,  0.6794,  0.2961, -0.7600, -0.6582],
        [-0.3992, -0.5696, -0.4995, -1.7815, -1.8028,  1.0145,  0.6170],
        [ 0.2151,  1.2339,  2.1758, -0.3407, -0.7374,  2.0502,  0.6479],
        [ 0.3274,  1.5631,  0.3789, -0.9754,  1.4382, -0.0709,  0.9929],
        [-0.9468,  1.3613, -1.4091, -0.7088, -0.0804, -2.2847,  0.6284],
        [ 1.4613, -1.3530, -0.3499,  0.0160,  0.6122, -0.3777,  1.4355],
        [ 1.2308, -0.9468,  0.4031,  0.0768,  1.3006,  0.8014,  0.9087]])

In [12]:
torch.normal(0, 1, size=(7, 7))

tensor([[ 1.0371,  0.1082,  0.5849,  0.2062,  0.4629,  1.0302,  0.7899],
        [ 0.2753,  0.3866, -0.6302,  1.9120,  0.6622, -0.4208, -1.1448],
        [-0.2988, -1.2171,  0.2384,  1.4582, -0.0478,  0.9091,  0.3999],
        [-0.1144,  0.4198,  1.9007,  0.8256, -0.0574,  0.5339,  0.8969],
        [-0.1121,  0.1217,  0.2426, -0.3741, -0.2408, -2.6425,  0.0633],
        [-0.7501,  0.6830, -0.8376, -0.3203,  1.1618, -0.4954,  0.1046],
        [ 0.2047, -0.7255,  0.6770, -0.2601, -0.2753,  0.4515, -1.1193]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
y = torch.rand(1, 7)
# Perform matrix multiplication
z = x @ y.T

In [24]:
print(y.shape)
print(x.shape)

torch.Size([1, 7])
torch.Size([7, 7])


In [26]:
z.shape

torch.Size([7, 1])

In [27]:
torch.matmul(x, y.T)

tensor([[2.0906],
        [1.8462],
        [1.4532],
        [1.9198],
        [2.1386],
        [2.3345],
        [1.8012]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [28]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(size=(7, 7))
y = torch.rand(size=(1, 7))

# Matrix multiply tensors
z = x @ y.T
print(z)
print(z.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [30]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [31]:
device = torch.device("mps")

In [32]:
# Set random seed
torch.manual_seed(1234)
x = torch.rand(size=(2, 3), device=device)
y = torch.rand(size=(2, 3)).to(device)

# Check for access to GPU

# Create two random tensors on GPU

print(x)
print(y)

tensor([[0.4794, 0.7608, 0.8283],
        [0.8029, 0.6423, 0.0597]], device='mps:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='mps:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [34]:
# Perform matmul on tensor_A and tensor_B
z = x @ y.T
print(z)

tensor([[0.5349, 0.8005],
        [0.2969, 0.3736]], device='mps:0')


In [59]:
n = 5 * 10**3

x = torch.rand(size=(n, n), device=device)
y = torch.rand(size=(n, n), device=device)

In [61]:
%timeit -n5 z = x @ y

215 μs ± 48.8 μs per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [62]:
n = 5 * 10**3

x = torch.rand(size=(n, n))
y = torch.rand(size=(n, n))

In [ ]:
%timeit -n5 z = x @ y

296 ms ± 14.5 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
max_value = torch.max(z)
print(max_value)

# Find min
min_value = torch.min(z)
print(min_value)


tensor(0.8005, device='mps:0')
tensor(0.2969, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [11]:
# Find arg max
argmax_value = torch.argmax(z)
print(argmax_value)

# Find arg min
argmin_value = torch.argmin(z)
print(argmin_value)


tensor(1, device='mps:0')
tensor(2, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [12]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
x_squeezed = torch.squeeze(x)

# Print out tensors and their shapes
print(f"Original tensor shape: {x.shape}")
print(f"Squeezed tensor shape: {x_squeezed.shape}")

Original tensor shape: torch.Size([1, 1, 1, 10])
Squeezed tensor shape: torch.Size([10])


In [13]:
x.flatten()

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [14]:
x.view(-1, 1)

tensor([[0.5349],
        [0.1988],
        [0.6592],
        [0.6569],
        [0.2328],
        [0.4251],
        [0.2071],
        [0.6297],
        [0.3653],
        [0.8513]])